#!/usr/bin/env node
// Bootstraps apps/web/.env for local development: copies .env.example (so newly
// added variables come along automatically) and fills in generated secrets.
// Idempotent — an existing .env is left untouched unless --force is passed.

import { randomBytes } from "node:crypto";
import { chmodSync, copyFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const examplePath = join(root, "apps", "web", ".env.example");
const envPath = join(root, "apps", "web", ".env");
const rel = (p) => relative(root, p);

const force = process.argv.slice(2).some((a) => a === "--force" || a === "-f" || a === "--overwrite");

const password = randomBytes(9).toString("base64url");
// Dev preset. AUTH_DISABLED skips login entirely, but a password is still generated so
// that flipping the flag to false is enough to exercise the real login flow.
const values = {
  APP_ENC_KEY: randomBytes(32).toString("hex"),
  AUTH_SECRET: randomBytes(32).toString("hex"),
  DASHBOARD_PASSWORD: password,
  AUTH_DISABLED: "true",
};

if (!existsSync(examplePath)) {
  console.error(`[setup:env] template not found: ${rel(examplePath)}`);
  process.exit(1);
}

const exists = existsSync(envPath);
if (exists && !force) {
  console.log(`[setup:env] ${rel(envPath)} already exists — left untouched.`);
  console.log(`[setup:env] regenerate with: pnpm run setup:env -- --force`);
  process.exit(0);
}

const pending = new Set(Object.keys(values));
const body = readFileSync(examplePath, "utf8")
  .split("\n")
  .map((line) => {
    const m = /^([A-Z0-9_]+)=/.exec(line);
    if (!m || !pending.has(m[1])) return line;
    pending.delete(m[1]);
    return `${m[1]}=${values[m[1]]}`;
  })
  .join("\n");

// A key the template no longer carries still has to end up in the file.
const orphans = [...pending].map((k) => `${k}=${values[k]}`);
const header =
  "# Generated by `pnpm setup:env` — LOCAL DEVELOPMENT ONLY.\n" +
  "# Regenerate: pnpm run setup:env -- --force. Never commit or ship this file.\n\n";
const out = `${header}${body}${orphans.length ? `\n${orphans.join("\n")}\n` : ""}`;

if (exists) {
  copyFileSync(envPath, `${envPath}.bak`);
  console.log(`[setup:env] backed up previous env → ${rel(envPath)}.bak`);
}
writeFileSync(envPath, out);
chmodSync(envPath, 0o600);

console.log(`[setup:env] wrote ${rel(envPath)}`);
console.log(`[setup:env]   APP_ENC_KEY / AUTH_SECRET   generated, 32 bytes each`);
console.log(`[setup:env]   AUTH_DISABLED=true          login skipped; set false to test the real flow`);
console.log(`[setup:env]   DASHBOARD_PASSWORD=${password}`);
console.log(`[setup:env] next: pnpm dev  →  http://localhost:3000`);
